import { Role } from "./Role.ts";
import { Emoji } from "./Emoji.ts";
import { Features } from "./Features.ts";
import { VoiceStates } from "./VoiceStates.ts";
import { GuildMember } from "./GuildMember.ts";
import { Channel } from "./Channels.ts";
export type Guild = {
  id: string;
  name: string;
  icon: string;
  icon_hash?: string;
  splash: string;
  discovery_splash: string;
  owner?: boolean;
  owner_id: string;
  permissions?: string;
  region?: string;
  afk_channel_id?: string;
  afk_timeout?: number;
  widget_channel_id?: string;
  widget_enabled?: boolean;
  verification_level?: number;
  default_message_notifications?: number;
  explicit_content_filter?: number;
  roles: Role[];
  emojis: Emoji[];
  features: Features[];
  mfa_level?: number;
  application_id?: string;
  system_channel_id?: string;
  system_channel_flags?: number;
  rules_channel_id?: string;
  joined_at?: string;
  large?: boolean;
  unavailable?: boolean;
  member_count?: number;
  voice_states: Partial<VoiceStates>[];
  members?: GuildMember[];
  channels?: Channel[];
  threads?: string[];
  presences?: string[];
  max_presences?: number;
  max_members?: number;
  vanity_url_code?: string;
  description: string;
  banner: string;
  premium_tier: number;
  premium_subscription_count?: number;
  preferred_locale: string;
  public_updates_channel_id: string;
  max_video_channel_users?: number;
  approximate_member_count?: number;
  approximate_presence_count?: number;
  welcome_screen?: string;
  nsfw_level?: number;
  stage_instances?: string[];
  stickers?: string[];
  guild_scheduled_events?: string[];
  premium_progress_bar_enabled?: boolean;
};
