import { APIGuild } from "../../types/mod.ts";
import { Camelize } from "../../../deps.ts";

interface GuildProperties extends Camelize<APIGuild> {}

export class Guild {
	iconHash: GuildProperties["iconHash"];
	discoverySplash: GuildProperties["discoverySplash"];
	owner: GuildProperties["owner"];
	ownerId: GuildProperties["ownerId"];
	permissions: GuildProperties["permissions"];
	region: GuildProperties["region"];
	afkChannelId: GuildProperties["afkChannelId"];
	afkTimeout: GuildProperties["afkTimeout"];
	widgetEnabled: GuildProperties["widgetEnabled"];
	widgetChannelId: GuildProperties["widgetChannelId"];
	verificationLevel: GuildProperties["verificationLevel"];
	defaultMessageNotifications: GuildProperties["defaultMessageNotifications"];
	explicitContentFilter: GuildProperties["explicitContentFilter"];
	roles: GuildProperties["roles"];
	emojis: GuildProperties["emojis"];
	features: GuildProperties["features"];
	mfaLevel: GuildProperties["mfaLevel"];
	systemChannelId: GuildProperties["systemChannelId"];
	systemChannelFlags: GuildProperties["systemChannelFlags"];
	rulesChannelId: GuildProperties["rulesChannelId"];
	joinedAt: GuildProperties["joinedAt"];
	large: GuildProperties["large"];
	memberCount: GuildProperties["memberCount"];
	voiceStates: GuildProperties["voiceStates"];
	members: GuildProperties["members"];
	channels: GuildProperties["channels"];
	threads: GuildProperties["threads"];
	presences: GuildProperties["presences"];
	maxPresences: GuildProperties["maxPresences"];
	maxMembers: GuildProperties["maxMembers"];
	vanityUrlCode: GuildProperties["vanityUrlCode"];
	description: GuildProperties["description"];
	banner: GuildProperties["banner"];
	premiumTier: GuildProperties["premiumTier"];
	premiumSubscriptionCount: GuildProperties["premiumSubscriptionCount"];
	preferredLocale: GuildProperties["preferredLocale"];
	publicUpdatesChannelId: GuildProperties["publicUpdatesChannelId"];
	maxVideoChannelUsers: GuildProperties["maxVideoChannelUsers"];
	approximateMemberCount: GuildProperties["approximateMemberCount"];
	approximatePresenceCount: GuildProperties["approximatePresenceCount"];
	welcomeScreen: GuildProperties["welcomeScreen"];
	nsfwLevel: GuildProperties["nsfwLevel"];
	stageInstances: GuildProperties["stageInstances"];
	stickers: GuildProperties["stickers"];
	premiumProgressBarEnabled: GuildProperties["premiumProgressBarEnabled"];
	guildScheduledEvents: GuildProperties["guildScheduledEvents"];
	hubType: GuildProperties["hubType"];
	name: string;
	icon: string | null;
	splash: string | null;
	unavailable: GuildProperties["unavailable"];
	id: GuildProperties["id"];
	constructor(d: any) {
		this.afkChannelId = d.afk_channel_id;
		this.afkTimeout = d.afk_timeout;
		this.approximateMemberCount = d.approximate_member_count;
		this.approximatePresenceCount = d.approximate_presence_count;
		this.banner = d.banner;
		this.channels = d.channels;
		this.defaultMessageNotifications = d.default_message_notifications;
		this.description = d.description;
		this.discoverySplash = d.discovery_splash;
		this.emojis = d.emojis;
		this.explicitContentFilter = d.explicit_content_filter;
		this.features = d.features;
		this.iconHash = d.icon_hash;
		this.id = d.id;
		this.joinedAt = d.joined_at;
		this.large = d.large;
		this.maxMembers = d.max_members;
		this.maxPresences = d.max_presences;
		this.maxVideoChannelUsers = d.max_video_channel_users;
		this.members = d.members;
		this.mfaLevel = d.mfa_level;
		this.name = d.name;
		this.owner = d.owner;
		this.ownerId = d.owner_id;
		this.premiumSubscriptionCount = d.premium_subscription_count;
		this.premiumTier = d.premium_tier;
		this.presences = d.presences;
		this.publicUpdatesChannelId = d.public_updates_channel_id;
		this.rulesChannelId = d.rules_channel_id;
		this.roles = d.roles;
		this.rulesChannelId = d.rules_channel_id;
		this.systemChannelId = d.system_channel_id;
		this.systemChannelFlags = d.system_channel_flags;
		this.systemChannelId = d.system_channel_id;
		this.vanityUrlCode = d.vanity_url_code;
		this.verificationLevel = d.verification_level;
		this.voiceStates = d.voice_states;
		this.widgetChannelId = d.widget_channel_id;
		this.widgetEnabled = d.widget_enabled;
		this.welcomeScreen = d.welcome_screen;
		this.nsfwLevel = d.nsfw_level;
		this.stageInstances = d.stage_instances;
		this.stickers = d.stickers;
		this.premiumProgressBarEnabled = d.premium_progress_bar_enabled;
		this.guildScheduledEvents = d.guild_scheduled_events;
		this.hubType = d.hub_type;
		this.icon = d.icon;
		this.splash = d.splash;
		this.unavailable = d.unavailable;
		this.verificationLevel = d.verification_level;
		this.region = d.region;
		this.preferredLocale = d.preferred_locale;
	}
}
